language: node_js
node_js:
  - "5.3"

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install
  - node_modules/.bin/typings install

script:
  - npm run travis
